### PR TITLE
Update _config.yml, navigation.yml; Add Events element

### PR DESCRIPTION
**Pull request by Shrikha1**
*  Update _config.yml : Added baseurl, corrected the repository
*  Remove website, facebook and github from left sidebar 
*  Add website link at the footer of the blog
*  Remove the added posts
*  Add an events element like posts 
*  Add events link in the navbar

### CODE REVIEW

**Comment by abhigyank** [comment]
Why is it `collection-archive` and not `events` . `events` in the url would be better.

**Comment by rishi-s8** [comment]
There are a few things that you should change.
- You have solved 2 issues and added 1 feature, all of them together in 1 PR. It would be better to make seperate PRs for seperate things.
- Your older commits should not be present in this PR.
- As mentioned by @abhigyank, the URL should be ```/events```.

**Comment by abhigyank** [comment]
> You have solved 2 issues and added 1 feature, all of them together in 1 PR. It would be better to make seperate PRs for seperate things.

Not an issue for now, I will cherry-pick the required commits. 
It'd be difficult for @Shrikha1  to fix the PR now, so I'll take care of that. Don't worry about it.

**Comment by rishi-s8** [comment]
The rest looks fine.

**Comment by abhigyank** [comment]
I have merged a most of the commits and initial structure for events is fine now.
Great job @Shrikha1 :rocket:  :tada:

**Pull request closed without merging**
