### PR TITLE
Navbar

### PR DESCRIPTION
**Pull request by Shrikha1**
* Added kamandprompt logo to the navbar
* Added blog link in the navbar

### CODE REVIEW

**Comment by Shrikha1** [comment]
screenshot from 2019-01-17 00-06-34
Now the site looks as shown in the screenshot.

**Comment by abhigyank** [comment]
@Shrikha1  I think we can remove the logo above the KamandPrompt on the left sidebar. Two consecutive logo's look bad.

@unkemptArc99  Can you review the SS if this addresses your issue?

**Comment by Shrikha1** [comment]
screenshot from 2019-01-17 16-42-07

**Comment by abhigyank** [comment]
Looks good to me. M<rging. Thanks @Shrikha1  :rocket:

**Pull request merged**
